"""add payroll wallets

Revision ID: 3aba946a1d86
Revises: bad1115bbe51
Create Date: 2026-05-31 20:12:55.088378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aba946a1d86'
down_revision: Union[str, None] = 'bad1115bbe51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_wallets',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('alatpay_wallet_id', sa.String(length=128), nullable=True),
    sa.Column('wallet_type', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=32), nullable=True),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('bank_name', sa.String(length=128), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'FAILED', name='wallet_status'), nullable=False),
    sa.Column('otp_tracking_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payroll_wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_wallets_business_id'), ['business_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_wallets_business_id'))

    op.drop_table('payroll_wallets')
    # ### end Alembic commands ###
