"""initial schema

Revision ID: bad1115bbe51
Revises: 
Create Date: 2026-05-31 19:47:22.090169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad1115bbe51'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('registration_number', sa.String(length=64), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('alatpay_business_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_businesses_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_businesses_name'), ['name'], unique=False)

    op.create_table('employees',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role', sa.String(length=128), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('salary', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('bank_name', sa.String(length=128), nullable=True),
    sa.Column('bank_account_number', sa.String(length=32), nullable=False),
    sa.Column('bank_account_name', sa.String(length=255), nullable=True),
    sa.Column('bank_routing_code', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='employee_status'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_business_id'), ['business_id'], unique=False)
        batch_op.create_index('ix_employees_business_id_status', ['business_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_email'), ['email'], unique=False)

    op.create_table('payroll_runs',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('period_label', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'FUNDING', 'PROCESSING', 'COMPLETED', 'PARTIALLY_COMPLETED', 'FAILED', 'CANCELLED', name='payroll_run_status'), nullable=False),
    sa.Column('total_funding_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alatpay_funding_reference', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alatpay_funding_reference')
    )
    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_runs_business_id'), ['business_id'], unique=False)

    op.create_table('transaction_receipts',
    sa.Column('payroll_run_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('distribution_state', sa.Enum('PENDING', 'PROCESSING', 'SUCCESSFUL', 'FAILED', 'REVERSED', name='distribution_state'), nullable=False),
    sa.Column('alatpay_transaction_reference', sa.String(length=128), nullable=True),
    sa.Column('bank_name', sa.String(length=128), nullable=True),
    sa.Column('bank_account_number', sa.String(length=32), nullable=True),
    sa.Column('bank_routing_code', sa.String(length=32), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_receipts_alatpay_transaction_reference'), ['alatpay_transaction_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_transaction_receipts_distribution_state'), ['distribution_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_receipts_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_receipts_payroll_run_id'), ['payroll_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_receipts_payroll_run_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_receipts_employee_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_receipts_distribution_state'))
        batch_op.drop_index(batch_op.f('ix_transaction_receipts_alatpay_transaction_reference'))

    op.drop_table('transaction_receipts')
    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_runs_business_id'))

    op.drop_table('payroll_runs')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_email'))
        batch_op.drop_index('ix_employees_business_id_status')
        batch_op.drop_index(batch_op.f('ix_employees_business_id'))

    op.drop_table('employees')
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_name'))
        batch_op.drop_index(batch_op.f('ix_businesses_email'))

    op.drop_table('businesses')
    # ### end Alembic commands ###
