// Static sample data used to render the scaffolded UI without a live backend.
// Swap these reads for the `api` client once the backend is connected.

import type { Employee, PayrollRun, TransactionReceipt } from "./types";

export const demoBusiness = {
  id: "biz_demo",
  name: "Jollof & Co. Kitchen",
  industry: "Food & Beverage",
};

export const demoEmployees: Employee[] = [
  {
    id: "emp_1",
    business_id: "biz_demo",
    first_name: "Amaka",
    last_name: "Okafor",
    email: "amaka@jollofco.ng",
    phone: "+234 801 234 5678",
    role: "Head Chef",
    department: "Kitchen",
    salary: "320000",
    currency: "NGN",
    bank_name: "GTBank",
    bank_account_number: "0123456789",
    bank_account_name: "Amaka Okafor",
    bank_routing_code: "058",
    status: "active",
  },
  {
    id: "emp_2",
    business_id: "biz_demo",
    first_name: "Tunde",
    last_name: "Bello",
    email: "tunde@jollofco.ng",
    phone: "+234 802 345 6789",
    role: "Cashier",
    department: "Front of House",
    salary: "150000",
    currency: "NGN",
    bank_name: "Access Bank",
    bank_account_number: "0987654321",
    bank_account_name: "Tunde Bello",
    bank_routing_code: "044",
    status: "active",
  },
  {
    id: "emp_3",
    business_id: "biz_demo",
    first_name: "Ngozi",
    last_name: "Eze",
    email: "ngozi@jollofco.ng",
    phone: "+234 803 456 7890",
    role: "Server",
    department: "Front of House",
    salary: "120000",
    currency: "NGN",
    bank_name: "Wema Bank",
    bank_account_number: "0456781234",
    bank_account_name: "Ngozi Eze",
    bank_routing_code: "035",
    status: "active",
  },
  {
    id: "emp_4",
    business_id: "biz_demo",
    first_name: "Sola",
    last_name: "Adeyemi",
    email: "sola@jollofco.ng",
    phone: "+234 804 567 8901",
    role: "Cleaner",
    department: "Operations",
    salary: "90000",
    currency: "NGN",
    bank_name: "UBA",
    bank_account_number: "0567812345",
    bank_account_name: "Sola Adeyemi",
    bank_routing_code: "033",
    status: "inactive",
  },
];

export const demoPayrollRuns: PayrollRun[] = [
  {
    id: "run_3",
    business_id: "biz_demo",
    period_label: "May 2026",
    status: "completed",
    total_funding_amount: "590000",
    currency: "NGN",
    employee_count: 3,
    executed_at: "2026-05-28T09:02:00Z",
    completed_at: "2026-05-28T09:03:12Z",
    created_at: "2026-05-28T08:55:00Z",
  },
  {
    id: "run_2",
    business_id: "biz_demo",
    period_label: "April 2026",
    status: "completed",
    total_funding_amount: "590000",
    currency: "NGN",
    employee_count: 3,
    executed_at: "2026-04-28T09:00:00Z",
    completed_at: "2026-04-28T09:01:40Z",
    created_at: "2026-04-28T08:50:00Z",
  },
  {
    id: "run_1",
    business_id: "biz_demo",
    period_label: "March 2026",
    status: "partially_completed",
    total_funding_amount: "590000",
    currency: "NGN",
    employee_count: 3,
    executed_at: "2026-03-28T09:00:00Z",
    completed_at: null,
    created_at: "2026-03-28T08:45:00Z",
  },
];

export const demoReceipts: TransactionReceipt[] = [
  {
    id: "rcpt_1",
    payroll_run_id: "run_3",
    employee_id: "emp_1",
    amount: "320000",
    currency: "NGN",
    distribution_state: "successful",
    alatpay_transaction_reference: "ALT-9X2K1A",
    processed_at: "2026-05-28T09:03:00Z",
    failure_reason: null,
  },
  {
    id: "rcpt_2",
    payroll_run_id: "run_3",
    employee_id: "emp_2",
    amount: "150000",
    currency: "NGN",
    distribution_state: "successful",
    alatpay_transaction_reference: "ALT-7P4M2B",
    processed_at: "2026-05-28T09:03:05Z",
    failure_reason: null,
  },
  {
    id: "rcpt_3",
    payroll_run_id: "run_3",
    employee_id: "emp_3",
    amount: "120000",
    currency: "NGN",
    distribution_state: "successful",
    alatpay_transaction_reference: "ALT-5Q9N3C",
    processed_at: "2026-05-28T09:03:10Z",
    failure_reason: null,
  },
];
