"use client";

import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { logoutUser, useAuth } from "@/lib/auth";
import { formatNaira, initials } from "@/lib/format";
import { logoutStaff, useStore } from "@/lib/store";

export default function ProfilePage() {
  const router = useRouter();
  const auth = useAuth();
  const { workers, payslips, currentStaffId, business } = useStore();
  const me = workers.find((w) => w.id === currentStaffId);
  const authUser = auth?.user.role === "staff" ? auth.user : null;

  if (!me && !authUser) return null;

  const displayFirst = me?.firstName ?? authUser!.firstName;
  const displayLast = me?.lastName ?? authUser!.lastName;
  const displayRole = me?.role ?? "Staff member";
  const employeeId = me?.id ?? authUser!.id;

  const mine = payslips.filter((p) => p.employeeId === employeeId);
  const totalEarned = mine.reduce((sum, p) => sum + p.net, 0);

  function downloadStatement() {
    const lines = [
      `PAYDAY — VERIFIED EARNINGS STATEMENT`,
      `Employee: ${displayFirst} ${displayLast} (${displayRole})`,
      `Employer: ${business.name}`,
      `Payslips on record: ${mine.length}`,
      `Total verified earnings: ${formatNaira(totalEarned)}`,
      `--------------------------------`,
      ...mine.map(
        (p) => `${p.period}: ${formatNaira(p.net)}  ref ${p.reference}`,
      ),
      `--------------------------------`,
      `This record is generated by Payday and may be shared with lenders or landlords.`,
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `earnings-statement-${displayLast}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  }

  function signOut() {
    logoutUser();
    logoutStaff();
    router.replace("/portal/login");
  }

  return (
    <div className="space-y-5">
      <header>
        <h1 className="text-xl font-semibold tracking-tight text-ink-900">
          Profile
        </h1>
        <p className="text-sm text-ink-400">Your details and earnings record.</p>
      </header>

      <Card className="flex flex-col items-center p-6 text-center">
        <div className="flex h-16 w-16 items-center justify-center rounded-full bg-brand-100 text-lg font-semibold text-brand-700">
          {initials(displayFirst, displayLast)}
        </div>
        <p className="mt-3 text-base font-semibold text-ink-900">
          {displayFirst} {displayLast}
        </p>
        <p className="text-sm text-ink-400">
          {displayRole} · {business.name}
        </p>
      </Card>

      <Card className="p-5">
        <p className="text-sm font-semibold text-ink-900">Verified earnings record</p>
        <p className="mt-1 text-xs text-ink-400">
          An auditable history of every salary paid — useful to unlock bank loans
          and formal tenancy applications.
        </p>
        <div className="mt-4 grid grid-cols-2 gap-3">
          <Stat label="Total earned" value={formatNaira(totalEarned)} />
          <Stat label="Payslips" value={String(mine.length)} />
        </div>
        <Button
          variant="secondary"
          className="mt-4 w-full"
          onClick={downloadStatement}
          disabled={mine.length === 0}
        >
          Download earnings statement
        </Button>
      </Card>

      <Card className="divide-y divide-ink-100">
        <Field label="Phone" value={me?.phone || authUser?.phone || "—"} />
        <Field label="Email" value={me?.email ?? authUser?.email ?? "—"} />
        {me ? (
          <>
            <Field label="Bank" value={me.bankName} />
            <Field label="Account" value={`••••${me.accountNumber.slice(-4)}`} />
          </>
        ) : null}
      </Card>

      <Button variant="ghost" className="w-full" onClick={signOut}>
        Sign out
      </Button>
    </div>
  );
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg bg-ink-50 p-3">
      <p className="text-xs text-ink-400">{label}</p>
      <p className="mt-0.5 text-base font-semibold tabular-nums text-ink-900">
        {value}
      </p>
    </div>
  );
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between px-5 py-3 text-sm">
      <span className="text-ink-400">{label}</span>
      <span className="font-medium text-ink-900">{value}</span>
    </div>
  );
}
